module.exports = [
  "FCUSTID",
  "FNumber",
  "FName",
  "FShortName",
  "FTEL",
  "F_PAEZ_Text1",
  "FFAX",
  "FADDRESS",
  "FCreateOrgId",
  "FUseOrgId",
  "FTRADINGCURRID",
  "FRECEIVECURRID"
  // "FCOUNTRY",
  // "FPROVINCIAL",
  // "FADDRESS",
  // "FZIP",
  // "FWEBSITE",
  // "FTAXREGISTERCODE",
  // "FCompanyClassify",
  // "FCompanyNature",
  // "FCompanyScale",
  // "FSUPPLIERID",
  // "FGROUPCUSTID",
  // "FIsGroup",
  // "FIsDefPayer",
  // "FCustTypeId",
  // "FGroup",
  // "FCorrespondOrgId",
  // "FTRADINGCURRID",
  // "FDescription",
  // "FSETTLETYPEID",
  // "FRECCONDITIONID",
  // "FPRICELISTID",
  // "FDISCOUNTLISTID",
  // "FTRANSLEADTIME",
  // "FTaxType",
  // "FInvoiceType",
  // "FTaxRate",
  // "FPriority",
  // "FRECEIVECURRID",
  // "FISCREDITCHECK",
  // "FIsTrade",
  // "FLagGroup",
  // "F_PAEZ_Text",
  // "F_PAEZ_Text1",
  // "FT_BD_CUSTOMEREXT",
  // "FT_BD_CUSTLOCATION",
  // "FT_BD_CUSTBANK",
  // "FT_BD_CUSTCONTACT",
  // "FT_BD_CUSTORDERORG"
]