module.exports = [
  "FID",
  "FBillTypeID",
  "FDATE",
  "FCONTACTUNITTYPE",
  "FCONTACTUNIT",
  "FPAYUNITTYPE",
  "FPAYUNIT",
  "FCURRENCYID",
  "FPAYORGID",
  "FDOCUMENTSTATUS",
  "FCancelStatus",
  "FSETTLECUR",
  "FRECEIVEBILLENTRY"
]
