module.exports = [
  "FID",
  "FBillTypeID",
  "FBillNo",
  // "FDate",
  // "FSaleOrgId",
  // "FCustId",
  // "FHeadDeliveryWay",
  // "FReceiveId",
  // "FHEADLOCID",
  // "FCorrespondOrgId",
  // "FSaleDeptId",
  // "FSaleGroupId",
  // "FSalerId",
  // "FReceiveAddress",
  // "FSettleId",
  // "FReceiveContact",
  // "FChargeId",
  // "FNetOrderBillNo",
  // "FNetOrderBillId",
  // "FOppID",
  // "FSalePhaseID",
  // "FISINIT",
  // "F_asd_Text",
  // "FNote",
  // "F_asd_Text1",
  // "F_asd_Text2",
  // "F_PAEZ_Text1",
  // "F_PAEZ_Base",
  // "F_PAEZ_Amount",
  // "FSaleOrderFinance",
  // "FSaleOrderClause",
  // "FSaleOrderEntry",
  // "FSaleOrderPlan",
  // "FSalOrderTrace",
  // "FSalOrderTraceDetail"
]
